#!/bin/bash

export MAGICK_HOME="$HOME/ImageMagick-7.0.10"
export PATH="$MAGICK_HOME/bin:$PATH"
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib/"

for D in *; do
    if [ -d "${D}" ]; then
      #echo "${D}"   # your processing here
      for filename in ./$D/*; do
        if [[ "$filename" == *"cover"* ]]; then
          magick "$filename" -strip -auto-orient -resize 300 "$filename"	
	else
          magick "$filename" -strip -auto-orient -resize 1300 "$filename"
        fi
      done
    fi
done
